# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy Node.js app to Azure Web App - hits-auth-server

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up Node.js version
        uses: actions/setup-node@v1
        with:
          node-version: "18.x"

      - name: npm install, build, and test
        run: |
          npm install
          npm run build --if-present
          npm run test --if-present

      - name: Upload auth server
        uses: actions/upload-artifact@v2
        with:
          name: auth-server
          path: ./apps/auth-server
      - name: Upload api proxy
        uses: actions/upload-artifact@v2
        with:
          name: api-proxy
          path: ./apps/api-proxy

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: "Production"
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download auth-server
        uses: actions/download-artifact@v2
        with:
          name: auth-server
          path: ./auth-server

      - name: Download api-proxy
        uses: actions/download-artifact@v2
        with:
          name: api-proxy
          path: ./api-proxy

      - name: "Deploy auth server"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "hits-auth-server"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_2D301BEF5A4C48F68617409F8E8D3AEE }}
          package: ./auth-server

      - name: "Deploy api proxy"
        uses: azure/webapps-deploy@v2
        with:
          app-name: "hits-api-proxy"
          slot-name: "Production"
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_83BA8BBDC89C4E67BE7D4787C8649135 }}
          package: ./api-proxy
